### ISSUE TITLE
[Feature] Profile Config Scene

### ISSUE THREAD

**Issue by LucaoMendes** [LucaoMendes/bet-bot#5]
### Cena de configuração do perfil de apostador

Nessa cena todo tipo de configuração necessária para apresentação das analises é feita.

**Fluxo:**

1. Usuário inicia o comando /start ou /profile
2. Ao entrar na cena apresentar um keyboard para seleção do valor minimo de odd começando em 1.00
3. Apresentar botões de + e - no caso: [ - 1.0, - 0.5, + 0.5 + 1.0 ] para ajustes das odds e ir atualizando no corpo da mensagem e o botão próximo embaixo
4. Solicitar o usuário configuração de odd Max começando sempre no valor superior ao valor minimo em 0.5
5. Apresentar botões de + e - no caso: [ - 1.0, - 0.5, + 0.5 + 1.0 ] para ajustes das odds e ir atualizando no corpo da mensagem e o botão próximo embaixo
6. Selecionar se ele deseja receber somente para times favoritos jogando em casa, fora ou ambos
7. Selecionar se ele deseja receber notificação durante a partida se sim ele pode escolher entre: começo da partida, meta batida ou final da partida
8. Selecionar valor de aposta: mesmo controle das odds porem de 5 em 5 começando em 10 reais
9. Selecionar quantidade máxima da múltipla a ser formada: ex quero multipla de no máximo 2 jogos, o bot monta as múltiplas nas condições das odds minimo 2 máx 5
10. Finalizar alterações
11. Apresentar alterações para o usuário, caso exista alguma estratégia anterior apresentar e mostrar as mudanças
12. Salvar informações e apresentar mensagem de salvamento ao usuário

**Tasks:**
- [x] Inicialização da cena por /start (através da action) ou /profile 
- [x] Seleção de Odd minima
- [x] Seleção de Odd Máxima
- [x] Seleção de prioridade dos times
- [x] Seleção de notificação durante partida
- [x] Selecionar quantidade máxima da multipla
- [x] Salvar alterações

**Comment by LucaoMendes** [comment]
Remoção da ideia por limitações tecnicas
**Apresentar botões de + e - no caso: [ - 1.0, - 0.5, + 0.5 + 1.0 ] para ajustes das odds e ir atualizando no corpo da mensagem e o botão próximo embaixo**
e o usuário agora insere o dado
